### ISSUE TITLE
Am looking for help with error

### ISSUE THREAD

**Issue by Swodzinski** [abayomi185/simple-pump-and-dump-bot#12]
Here's the error's

 Traceback (most recent call last):
  File "C:\Users\theba\Python\lib\site-packages\PyInquirer\prompt.py", line 69, in prompt
    answer = run_application(
  File "C:\Users\theba\Python\lib\site-packages\prompt_toolkit\shortcuts.py", line 576, in run_application
    output=create_output(true_color=true_color))
  File "C:\Users\theba\Python\lib\site-packages\prompt_toolkit\shortcuts.py", line 118, in create_output
    return Win32Output(stdout)
  File "C:\Users\theba\Python\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 80, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Users\theba\Python\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 162, in get_win32_screen_buffer_info
    self.flush()
  File "C:\Users\theba\Python\lib\site-packages\prompt_toolkit\terminal\win32_output.py", line 288, in flush
    self.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theba\Documents\simple-pump-and-dump-bot\src\bot-kucoin.py", line 277, in <module>
    answer1 = Inquirer.prompt(question1)
  File "C:\Users\theba\Python\lib\site-packages\PyInquirer\prompt.py", line 88, in prompt
    raise ValueError('No question type \'%s\'' % type)
ValueError: No question type 'list'

**Comment by abayomi185** [comment]
Please see this issue thread. #9

https://github.com/abayomi185/simple-pump-and-dump-bot/issues/9#issuecomment-838442179

**Comment by abayomi185** [comment]
You shouldn't need to modify the bot. Ensure that the name of the config file and secret file are correct and they are in the same directory as the bot Python file.

I'm unable to tell otherwise what the error you sent might be.

**Comment by Swodzinski** [comment]
they are all under the same directory, any other thoughts as to what could cause this issue?

**Comment by Swodzinski** [comment]
okay almost got it fully operational this is the last bit of code thats throwing errors:
Traceback (most recent call last):
  File "C:\Users\theba\Documents\simple-pump-and-dump-bot\src\bot-kucoin.py", line 284, in <module>
    balance = acct_balance()
  File "C:\Users\theba\Documents\simple-pump-and-dump-bot\src\bot-kucoin.py", line 99, in acct_balance
    acct_balance = user_client.get_account_list(config['trade_configs'][selected_config]['pairing'], 'trade')
  File "C:\Users\theba\Python\lib\site-packages\kucoin\user\user.py", line 115, in get_account_list
    return self._request('GET', '/api/v1/accounts', params=params)
  File "C:\Users\theba\Python\lib\site-packages\kucoin\base_request\base_request.py", line 93, in _request
    return self.check_response_data(response_data)
  File "C:\Users\theba\Python\lib\site-packages\kucoin\base_request\base_request.py", line 112, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 401-{"code":"400003","msg":"KC-API-KEY not exists"}
