### ISSUE TITLE
Using WSL2 

### ISSUE THREAD

**Issue by Swodzinski** [abayomi185/simple-pump-and-dump-bot#16]
database files open fine in windows, but when I  run in WSL2, it doesn't run properly. Any ideas as to what I am missing ?
File "/home/sampi314/.docker/simple-pump-and-dump-bot/src/initialise_db.py", line 3, in <module>
    conn = sqlite3.connect('"C:\\users\\guest\\desktop\\example.db")/usr/bin/python3/home/sampi314/.docker/simple-pump-and-dump-bot/src/records.db')
sqlite3.OperationalError: unable to open database file

**Comment by abayomi185** [comment]
Check the file permissions and ownership for the database in your Linux terminal. It should be accessible by your Linux user.

**Comment by Swodzinski** [comment]
got that resolved, I think I'm right on the brink of getting it up and running. This is the last of the errors I believe it will throw
Traceback (most recent call last):
  File "/home/sampi314/simple-pump-and-dump-bot/simple-pump-and-dump-bot/src/bot-kucoin.py", line 281, in <module>
    balance = acct_balance()
  File "/home/sampi314/simple-pump-and-dump-bot/simple-pump-and-dump-bot/src/bot-kucoin.py", line 93, in acct_balance
    acct_balance = user_client.get_withdrawal_quota(config['trade_configs']
  File "/home/sampi314/.local/lib/python3.8/site-packages/kucoin/user/user.py", line 645, in get_withdrawal_quota
    return self._request('GET', '/api/v1/withdrawals/quotas', params=params)
  File "/home/sampi314/.local/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 93, in _request
    return self.check_response_data(response_data)
  File "/home/sampi314/.local/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 112, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 401-{"code":"400003","msg":"KC-API-KEY not exists"}

**Comment by abayomi185** [comment]
The error shows the API is connected but the API key does not exist. It is possible you have a new V2 API key that the bot does not currently support. See issue #10

**Comment by Swodzinski** [comment]
thank you for your help!

**Comment by Swodzinski** [comment]
Lmao I lied fingers crossed its smooth sailing once I get this error taken care of
Traceback (most recent call last):
  File "/home/sampi314/simple-pump-and-dump-bot/simple-pump-and-dump-bot/src/bot-kucoin.py", line 282, in <module>
    balance = acct_balance()
  File "/home/sampi314/simple-pump-and-dump-bot/simple-pump-and-dump-bot/src/bot-kucoin.py", line 99, in acct_balance
    print('\nYour {} balance is {}\n'.format(config['trade_configs'][selected_config]['pairing'], acct_balance[1]['available']))
KeyError: 1

**Comment by abayomi185** [comment]
Haha. Do you have your crypto pairing in your trading account?

**Comment by Swodzinski** [comment]
I didnt't realize it would throw an error if I didnt have any in there already. I'll give an update when I convert to usdt

**Comment by abayomi185** [comment]
You can change the pairing if you have some other crypto.

For my use case, I omitted error handling as it could slow down the script if not implemented properly. I also didn't find it necessary to have.
