### ISSUE TITLE
I got sometimes this error

### ISSUE THREAD

**Issue by nauj151** [abayomi185/simple-pump-and-dump-bot#18]
Hi,
Its ok the bot working functionally, but sometimes I get this error? What it means

Traceback (most recent call last):
  File "bot-kucoin.py", line 243, in <module>
    buy_order = market_order(selected_coin_pair, 'buy')
  File "bot-kucoin.py", line 144, in market_order
    order_id = trade.create_market_order(selected_coin_pair, 'buy', clientOid=str(uuid.uuid4()), size=str(buy_qty))
  File "/home/user/.local/lib/python3.6/site-packages/kucoin/trade/trade.py", line 164, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/home/user/.local/lib/python3.6/site-packages/kucoin/base_request/base_request.py", line 93, in _request
    return self.check_response_data(response_data)
  File "/home/user/.local/lib/python3.6/site-packages/kucoin/base_request/base_request.py", line 110, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"300000","msg":"Order size invalid."}

**Comment by abayomi185** [comment]
Your order size is invalid. Kucoin has restrictions to how much or little you can trade. Modify your config file or check funds in your account.
