### ISSUE TITLE
new error after buying a coin

### ISSUE THREAD

**Issue by outrageousmaski** [abayomi185/simple-pump-and-dump-bot#19]
Traceback (most recent call last):
  File "bot-kucoin.py", line 297, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bot-kucoin.py", line 252, in main
    insert_into_db(order=buy_order_data, order_id=buy_order['orderId'])
  File "bot-kucoin.py", line 216, in insert_into_db
    c.execute("INSERT INTO Orders VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
sqlite3.OperationalError: no such table: Orders

**Comment by abayomi185** [comment]
Hey, did you run initialise_db.py ?

**Comment by abayomi185** [comment]
Thanks for helping with the other issue!
