### ISSUE TITLE
binance error

### ISSUE THREAD

**Issue by rulezzpt** [abayomi185/simple-pump-and-dump-bot#20]
Hello,

When i run the bot in WSL i have this errors.

-- Binance Edition --

? Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File "bot-binance.py", line 249, in <module>
    balance = acct_balance()
  File "bot-binance.py", line 88, in acct_balance
    acct_balance = client.get_asset_balance(asset=config['trade_configs']
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 1979, in get_asset_balance
    res = self.get_account(**params)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 1954, in get_account
    return self._get('account', True, data=params)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 365, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 328, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 309, in _request
    return self._handle_response(self.response)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 318, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

I check everything and i cannot understand why, i have secrets and a valid api but cannot put the bot running.

Thanks.

**Comment by abayomi185** [comment]
Hey, see this issue thread

https://github.com/sammchardy/python-binance/issues/249

**Comment by rulezzpt** [comment]
Thanks, problem solved!
