### ISSUE TITLE
 Facing error while running -  API key not found

### ISSUE THREAD

**Issue by Alphanito** [abayomi185/simple-pump-and-dump-bot#24]
Traceback (most recent call last):
  File "C:\Users\Asus\simple-pump-and-dump-bot\src\bot-kucoin.py", line 275, in <module>
    balance = acct_balance()
  File "C:\Users\Asus\simple-pump-and-dump-bot\src\bot-kucoin.py", line 92, in acct_balance
    acct_balance = user_client.get_account_list(config['trade_configs'][selected_config]['pairing'], 'trade')
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\kucoin\user\user.py", line 115, in get_account_list
    return self._request('GET', '/api/v1/accounts', params=params)
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\kucoin\base_request\base_request.py", line 93, in _request
    return self.check_response_data(response_data)
  File "C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\kucoin\base_request\base_request.py", line 112, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 401-{"code":"400003","msg":"KC-API-KEY not exists"}

**Comment by abayomi185** [comment]
Hey, I presume you have a V2 API key? The bot does not currently support this, sorry.

A new version will be out in a day or two that supports V2 API keys

**Comment by Alphanito** [comment]
Thanks

**Comment by abayomi185** [comment]
Hey, I realised my key is a V2 key and you shouldn't have issues using a V2 API key. You may want to check that your other api details are correct.

**Comment by Alphanito** [comment]
Thanks, I'll check it out. Also if it doesn't workout, I will contact you.
Is it possible that when you are available, we can arrange a discord call,
you can walk me through it, if I am unable to detect the problem. Thanks.
Regards,
Yash
