### ISSUE TITLE
Cannot improt market usr local lib

### ISSUE THREAD

**Issue by Maskiplays** [abayomi185/simple-pump-and-dump-bot#3]
python3 bot-kucoin.py installed but new issue comes up
root@ubuntu:/home/max/simple-pump-and-dump-bot/src# python3 bot-kucoin.py
Traceback (most recent call last):
  File "bot-kucoin.py", line 18, in <module>
    from kucoin.client import Market
ImportError: cannot import name 'Market' from 'kucoin.client' (/usr/local/lib/python3.8/dist-packages/kucoin/client.py)
root@ubuntu:/home/max/simple-pump-and-dump-bot/src#

**Comment by abayomi185** [comment]
Hey, try this instead;

```pip install kucoin-python```

I mixed up the packages

This one is the official package
https://github.com/Kucoin/kucoin-python-sdk

**Comment by Maskiplays** [comment]
now i get this error: root@ubuntu:/home/max/simple-pump-and-dump-bot/src# python3 bot-kucoin.py
Traceback (most recent call last):
  File "bot-kucoin.py", line 38, in <module>
    config = yaml.safe_load(conf_file)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./conf-kucoin.yaml", line 7, column 11
root@ubuntu:/home/max/simple-pump-and-dump-bot/src#
