### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlphaAlex1** [abayomi185/simple-pump-and-dump-bot#33]
Hey, I am getting this error while running the bot. Is there something I am doing wrong?

Traceback (most recent call last):
  File "c:\Users\aqibi\Desktop\simple-pump-and-dump-bot-master\src\bot-kucoin.py", line 39, in <module>
    config = yaml.safe_load(conf_file)
  File "D:\Apps\Python\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "D:\Apps\Python\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "D:\Apps\Python\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 36, in get_single_node 
    document = self.compose_document()
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 84, in compose_node    
    node = self.compose_mapping_node(anchor)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\Apps\Python\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "D:\Apps\Python\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\Apps\Python\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "D:\Apps\Python\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "D:\Apps\Python\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "D:\Apps\Python\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\aqibi\Desktop\simple-pump-and-dump-bot-master\src\conf-kucoin.yaml", line 27, column 5
could not find expected ':'
  in "C:\Users\aqibi\Desktop\simple-pump-and-dump-bot-master\src\conf-kucoin.yaml", line 28, column 5

Will appreciate any help!

**Comment by abayomi185** [comment]
Hey, are you running this in a terminal/prompt?

I would recommend using WSL for the Python bot too.

**Comment by AlphaAlex1** [comment]
using visual studio, but i get the same error running this in a terminal

**Comment by AlphaAlex1** [comment]
Anything I could do here?

**Comment by swordapi** [comment]
I have the same problem on termux
