### ISSUE TITLE
[Node.js] Error when using Telegram scraper

### ISSUE THREAD

**Issue by nikeboy264** [abayomi185/simple-pump-and-dump-bot#42]
Hi @abayomi185,

I'm trying to make telegram scraper works, but no luck (manual mode working fine).

Below is the error message, Please help.

> node bot.js

file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:1273
  return new exception(message, mark);
         ^
YAMLException: bad indentation of a mapping entry (29:13)

 26 |   api_hash: ###MASKING###
 27 |   groups:
 28 |     pump_group_1: 123456
 29 |       prefix: "" # "The coin is: " in "The  ...
------------------^
 30 |       special_character: "" # '$' in $DOGE
 31 |       suffix_to_split: "" # "-" in DOGE-USD ...
    at generateError (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockMapping (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2254:11)
    at composeNode (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readDocument (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///C:/Users/Bot/simple-pump-and-dump-bot/node_wip/node_modules/js-yaml/dist/js-yaml.mjs:2778:5) {
  reason: 'bad indentation of a mapping entry',

**Comment by abayomi185** [comment]
Hey, the telegram scraper is not complete yet but it shouldn't give you errors like this.

This is a yaml error. Check your indentation
