### ISSUE TITLE
YAML Parse Error

### ISSUE THREAD

**Issue by manuelinfosec** [abayomi185/simple-pump-and-dump-bot#45]
I am stuck with an error on executing the “bot-binance.py”, shows me some kind of yaml parse error. Check it out:

```
Traceback (most recent call last):
  File "C:\Users\user\Manuel Files\Projects\Production\sniper-td\src\bot-binance.py", line 40, in <module>
    api_keys = yaml.safe_load(secrets_file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "./secrets-binance.yaml", line 3, column 1
```

I'd be grateful if there is a fix for this issue, or is it just me?

P.S: I'm running it on a Windows machine.

**Comment by abayomi185** [comment]
Hey, could you check your yaml syntax and indentation?

I may help if you obfuscate your api secrets and show the contents of your secrets file.

Have you considered using WSL?

**Comment by manuelinfosec** [comment]
```
"api_key: '*****************************************************************'" 
"api_secret: '********************************************************'" 
```

This is the content of the secrets-binance.yaml file

**Comment by abayomi185** [comment]
Perhaps try the bot without the quotes for your api_key and api_secret.

**Comment by manuelinfosec** [comment]
That was easy. Thanks!
