### ISSUE TITLE
error when runnning node ./src/scrapers/telegram-register.js

### ISSUE THREAD

**Issue by geeks121** [abayomi185/simple-pump-and-dump-bot#54]
i'm facing error when run node ./src/scrapers/telegram-register.js

here is the log : 
`Telegram API details incomplete or not found
users.getFullUser error: TypeError: Cannot read property 'call' of undefined
    at TelegramScraper.call (file:///home/root/bot/pump/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram.js:58:42)
    at getUser (file:///home/root/bot/pump/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:13:28)
    at file:///home/root/bot/pump/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:67:22
    at file:///home/root/bot/pump/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:138:3
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
? Please input your number with the country code; e.g +44XXX`

**Comment by abayomi185** [comment]
Hey, you may proceed with inputting your telegram number. The code is from the telegram mproto documentation and I didn’t check the errors as it works as intended

**Comment by geeks121** [comment]
bot without number and with phone number, have same error for me.
