### ISSUE TITLE
Error with telegram-register.js

### ISSUE THREAD

**Issue by rayphoon88** [abayomi185/simple-pump-and-dump-bot#57]
root@python01:/usr/local/repos/simple-pump-and-dump-bot/node_wip# node ./src/scrapers/telegram-register.js
users.getFullUser error: TypeError: Cannot read properties of undefined (reading 'call')
    at TelegramScraper.call (file:///usr/local/repos/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram.js:58:42)
    at getUser (file:///usr/local/repos/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:13:28)
    at file:///usr/local/repos/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:67:22
    at file:///usr/local/repos/simple-pump-and-dump-bot/node_wip/src/scrapers/telegram-register.js:138:3
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
? Please input your number with the country code; e.g +44XXX +61xxxxxxxx
? Please enter your login code xxxxx
auth.signIn error: {
  _: 'mt_rpc_error',
  error_code: 406,
  error_message: 'UPDATE_APP_TO_LOGIN'
}
error: {
  _: 'mt_rpc_error',
  error_code: 406,
  error_message: 'UPDATE_APP_TO_LOGIN'
}

**Comment by rayphoon88** [comment]
Telegram api_id and api_hash already configured in conf.yaml.
