### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by outrageousmaski** [abayomi185/simple-pump-and-dump-bot#8]
? Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcda1753490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kucoin.com', port=443): Max retries exceeded with url: /api/v1/accounts?currency=USDT&type=trade (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcda1753490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot-kucoin.py", line 227, in <module>
    balance = acct_balance()
  File "bot-kucoin.py", line 95, in acct_balance
    acct_balance = user_client.get_account_list(config['trade_configs'][selected_config]['pairing'], 'trade')
  File "/usr/local/lib/python3.8/dist-packages/kucoin/user/user.py", line 73, in get_account_list
    return self._request('GET', '/api/v1/accounts', params=params)
  File "/usr/local/lib/python3.8/dist-packages/kucoin/base_request/base_request.py", line 86, in _request
    response_data = requests.request(method, url, headers=headers, timeout=timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.kucoin.com', port=443): Max retries exceeded with url: /api/v1/accounts?currency=USDT&type=trade (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcda1753490>: Failed to establish a new

**Comment by Maskiplays** [comment]
Still the error put the refresh time 20

**Comment by abayomi185** [comment]
You may have to wait for a period of time before Kucoin servers accept your requests again.

Yes 1.5 is 50% gain

**Comment by Maskiplays** [comment]
how long i tried with vpn and it sill does not work

**Comment by Maskiplays** [comment]
Is 1.05 5% gain or does this not work?

**Comment by Maskiplays** [comment]
yea because i just ried it the coin went up 7% the bot didnt sell

**Comment by abayomi185** [comment]
Due to volatility, It depends on the price at the moment the bot checks for the price

**Comment by abayomi185** [comment]
There's an issue with the bot checking the price during the pump. I'm fixing it now

**Comment by Maskiplays** [comment]
yea i was thinking about that thats why i biought with it and sold mannualy but the bot would have mad 200% and i only made  20 but thas okay its in work

**Comment by Maskiplays** [comment]
how long would this take i am always up for testing

**Comment by abayomi185** [comment]
I should get it done in the next few hours

**Comment by outrageousmaski** [comment]
how is it going any update? do you know how to fix it?

**Comment by abayomi185** [comment]
Yes, I'm mostly there. I'm implementing asyncio for asynchronous function calls

**Comment by outrageousmaski** [comment]
Just tell me when its done

**Comment by outrageousmaski** [comment]
and how does it look

**Comment by abayomi185** [comment]
This video gives a brief using Python. 
https://www.youtube.com/watch?v=t5Bo1Je9EmE

I was using threads before and while that can work, I didn't realise it wasn't implemented properly.

**Comment by abayomi185** [comment]
Repo is updated and new version is live. I have done some testing but please do some testing too. I would like to know if it works well for Kucoin and Binance.

The config file works as intended now. The bot will check for price changes during the process rather than waiting for the set time. You can test this for yourself by uncommenting line 180 for Kucoin and line 169 for Binance.

There is also a timer implemented after the trade to show if the bot was able to sell before the fallback time.

**Comment by abayomi185** [comment]
@outrageousmaski have you updated and tested it out yet?

**Comment by outrageousmaski** [comment]
updated yes tested no didnt get the opertunity
